<?xml version="1.0"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
	version="2.0">
	<xsl:output method="html" encoding="utf-8" indent="yes" />
	<xsl:template match="/">
		<xsl:text disable-output-escaping='yes'>&lt;!DOCTYPE html&gt;</xsl:text>
		<HTML>
			<HEAD>
			    <title><xsl:value-of select="Report/@RunFlow"></xsl:value-of> Test Results - Generated by ItJumpStart framework</title>
				<link TYPE="text/css" href="css/Report.css" rel="StyleSheet"/>
				<script src="js/jquery-1.6.4.min.js"></script>
				<script src="js/Chart.min.js"></script>
				<script type="text/javascript" src="js/jquery.ui.core.min.js"></script>
				<script type="text/javascript" src="js/jquery.ui.widget.min.js"></script>
				<script type="text/javascript" src="js/jquery.ui.rlightbox.min.js"></script>
				<link type="text/css" rel="stylesheet" href="css/jquery-ui-1.8.16.custom.css" />
				<link type="text/css" rel="stylesheet" href="css/lightbox.min.css" />
				<script type="text/javascript">
    				jQuery(function($) {
						$( ".lb_failures" ).rlightbox();
    				});
				</script>
				<SCRIPT language="javascript" type="text/javascript">
					function toggleMenu(id,x) {
						if (document.getElementById) {
							var e = document.getElementById(id);
							var b = document.getElementById(x);
							if (e) {
								if (e.style.display != "block") {
									e.style.display = "block";
									b.src="img/Minus.ico";
								}else {
									e.style.display = "none";
									b.src="img/Plus.ico";
								}
							}
						}
					}

					function expandall() {
						var expand= document.getElementById("expand");
						var collapse = document.getElementById("collapse");
						expand.style.display = "none";
						collapse.style.display = "inline";
						var e = document.getElementById("container").getElementsByTagName("DIV");
						var b = document.getElementById("container").getElementsByTagName("img");
	
						for (var i = 0; i &lt; e.length; i++) {
							if (e[i].style.display == "none") {
								e[i].style.display = "block";
							}
						}
						for (var i = 0; i &lt; b.length; i++) {
							if (b[i].id != "m1" &amp;&amp; b[i].id != "m2") {
								if (b[i].src.substring(b[i].src.length-8, b[i].src.length) == "Plus.ico") {
									b[i].src = "img/Minus.ico";
								}
							}
						}
					}

					function expandtofailure(id) {
						var parent = document.getElementById(id);
						var all = parent.getElementsByTagName('div');
						var icon = parent.getElementsByTagName("img");
	
						for (var i = 0; i &lt; all.length; i++) {
							all[i].style.display = "block";
						}
						for (var i = 0; i &lt; all.length; i++) {
							icon[i].src="file:///C:/Program Files/Reporting/img/Minus.ico";
						}
					}

					function collapseall() {
						var expand=	document.getElementById("expand");
						var collapse= document.getElementById("collapse");
						expand.style.display = "inline";
						collapse.style.display = "none";
						var e = document.getElementsByTagName("DIV");
						var b =	document.getElementsByTagName("img");
	
						for (var i = 0; i &lt; e.length; i++) {
							if(e[i].id!="DIV1.0" &amp;&amp; e[i].id != "TestCase" &amp;&amp; e[i].id != "TestActivity" &amp;&amp; e[i].id != "TestMethod" &amp;&amp; e[i].id != "TestSubMethod" &amp;&amp; e[i].id != "MethodResult" &amp;&amp; e[i].id != "SubMethodResult")
							{
								if (e[i].style.display == "block") {
								e[i].style.display = "none";
								}
							}
						}
						for (var i = 0; i &lt; b.length; i++) {
							if (b[i].id != "m1" &amp;&amp; b[i].id != "m2") {
								if(b[i].src.substring(b[i].src.length-9, b[i].src.length) == "Minus.ico") {
									b[i].src = "img/Plus.ico";
								}
							}
						}
					}

					function drawPie() {
						var data = [ {
						value :
						<xsl:value-of
							select="(count(Report/TestCase/TestActivity/TestMethod/MethodResult[@Status='0']) + count(Report/TestCase/TestActivity/TestMethod/MethodResult[@Status='20']) + count(Report/TestCase/TestActivity/TestMethod/TestSubMethod/SubMethodResult[@Status='0']) + count(Report/TestCase/TestActivity/TestMethod/TestSubMethod/SubMethodResult[@Status='20']))"></xsl:value-of>
						,
						color : "#F7464A",
						highlight : "#FF5A5E",
						label : "Failed"
						}, {
						value
						:
						<xsl:value-of
							select="(count(Report/TestCase/TestActivity/TestMethod/MethodResult[@Status='1']) + count(Report/TestCase/TestActivity/TestMethod/MethodResult[@Status='21']) + count(Report/TestCase/TestActivity/TestMethod/TestSubMethod/SubMethodResult[@Status='1']) + count(Report/TestCase/TestActivity/TestMethod/TestSubMethod/SubMethodResult[@Status='21']))"></xsl:value-of>
						,
						color : "#46BFBD",
						highlight : "#5AD3D1",
						label : "Passed"
						}, {
						value
						:
						<xsl:value-of
							select="(count(Report/TestCase/TestActivity/TestMethod/MethodResult[@Status='2']) + count(Report/TestCase/TestActivity/TestMethod/TestSubMethod/SubMethodResult[@Status='2']))"></xsl:value-of>
						,
						color : "#FDB45C",
						highlight : "#FFC870",
						label : "Skipped"
						} ];

						var ctx = document.getElementById("myChart").getContext("2d");
						var	myPieChart = new Chart(ctx).Pie(data, {
								animateScale : true,
							});
						var	legent = myPieChart.generateLegend();
						var div = document.getElementById("legend");
						div.innerHTML = "<BR></BR>";
						div.innerHTML = div.innerHTML+ "<BR></BR>"+legent;
					}
				</SCRIPT>
			</HEAD>
			<BODY onload="drawPie();">
				<div id="container" class="centerIt">
					<table border="0" width="100%" height="45" class="heading">
						<tr height="21">
							<td bgcolor="#ffffff" valign="center" align="center" width="10%">
								<img src="img/Logo.jpeg"></img>

							</td>
							<td valign="center" align="center" width="80%">
								<p align="center">
									<xsl:value-of select="Report/@ApplicationName"></xsl:value-of>
								</p>
							</td>
						</tr>
					</table>
					<BR></BR>
					<TABLE bordercolorlight="#C0C0C0" bordercolordark="#C0C0C0"
						border="1" cellSpacing="1" cellPadding="2" align="center" Class="EnvHeader">
						<TR class="message">
							<TD width="20%">ENVIRONMENT</TD>
							<TD width="30%" Class="celltextcolor">
								<xsl:value-of select="Report/@Env"></xsl:value-of>
							</TD>
							<TD width="25%">EXECUTION DATE</TD>
							<TD width="25%" Class="celltextcolor">
								<xsl:value-of select="Report/@DateTime"></xsl:value-of>
							</TD>
						</TR>
					</TABLE>
					<TABLE bordercolorlight="#C0C0C0" bordercolordark="#C0C0C0"
						border="1" cellSpacing="1" cellPadding="2" align="center" Class="EnvHeader">
						<TR class="message">
							<TD width="20%">SUIT NAME</TD>
							<TD width="30%" Class="celltextcolor">
								<xsl:value-of select="Report/@RunFlow"></xsl:value-of>
							</TD>
							<TD width="25%">BUILD VERSION</TD>
							<TD width="25%" Class="celltextcolor">
								<xsl:value-of select="Report/@BuildVersion"></xsl:value-of>
							</TD>
						</TR>
					</TABLE>
					<TABLE bordercolorlight="#C0C0C0" bordercolordark="#C0C0C0"
						border="1" cellSpacing="1" cellPadding="1" align="center" Class="EnvHeader">
						<TR class="message">
							<TD width="20%">SCREENSHOT</TD>
							<TD width="30%" Class="celltextcolor">
								<xsl:value-of select="Report/@Screenshot"></xsl:value-of>
							</TD>
							<TD width="25%">VIDEO RECORDING</TD>
							<TD width="25%" Class="celltextcolor">
								<xsl:value-of select="Report/@Video"></xsl:value-of>
							</TD>
						</TR>
					</TABLE>
					<BR />
					<div id="summary">Run Summary</div>
					<div id="graph">
						<canvas id="myChart" align="right">Your Browser doesn't support
							HTML5 graph</canvas>
					</div>
					<div id="legend"></div>
					<BR></BR>
					<TABLE width="80%" cellSpacing="1" cellPadding="1" align="center"
						Class="PrevNext">
						<TR>
							<TD id="expand" style="display:inline;" width="10%"
								onClick="expandall();return false;">
								<img href="#" src="img/Plus.ico"
									id="m1" class="toggle" />
								<a href="#">Expand All</a>
							</TD>
							<TD id="collapse" style="display:none;" width="10%"
								onClick="collapseall();return false;">
								<img src="img/Minus.ico" id="m2"
									class="toggle"></img>
								<a href="#">Collapse All</a>
							</TD>
							<td width="75%" align="right" style="padding-right:20px;">
								<b>
									Test Run by
									<xsl:text> </xsl:text>
									<xsl:value-of select="Report/@User"></xsl:value-of>
									<xsl:text>@</xsl:text>
									<xsl:value-of select="Report/@Host"></xsl:value-of>
								</b>
							</td>
						</TR>
					</TABLE>
					<BR></BR>
					<div class="results">
						<xsl:apply-templates select="Report/TestCase"></xsl:apply-templates>
					</div>
					<div id="footer"
						style="clear:both;text-align:center;background-color:white;font-size:11px;font-family:Palatino;">Designed by Nainappa Illi. 
						Best viewed in IE9 @ 1366 x 768 resolution</div>
				</div>
			</BODY>
		</HTML>
	</xsl:template>

	<xsl:template match="Report/TestCase">
		<DIV id="TestCase" Style="POSITION: relative; display:block"
			class="tablehead">
			<TABLE cellSpacing="1" cellPadding="1" align="Left" Class="TestCase"
				onClick="">
				<TR align="Left">
					<TD class="message" style="width:30%;">
						<xsl:choose>
							<xsl:when test="@TCStatus='0'"> <!-- Test Failed -->
								<img src="img/False.ico"
									class="toggle" style="padding-right:20px;padding-left:5px"></img>
							</xsl:when>
							<xsl:when test="@TCStatus='10'"> <!-- Test Errored -->
								<img src="img/False.ico"
									class="toggle" style="padding-right:20px;padding-left:5px"></img>
							</xsl:when>
							<xsl:when test="@TCStatus='2'"> <!-- Test Skipped -->
								<img src="img/skip.ico"
									class="toggle" style="padding-right:20px;padding-left:5px"></img>
							</xsl:when>
							<xsl:otherwise> <!-- Test Passed -->
								<img src="img/True.ico"
									class="toggle" style="padding-right:20px;padding-left:5px"></img>
							</xsl:otherwise>
						</xsl:choose>
						<!--<img id="m{position()}.0" src="file:///C:/Program Files/Reporting/img/Plus.ico" 
							border="0" class="toggle"/> -->
						<xsl:value-of select="@Desc"></xsl:value-of>
					</TD>
					<TD class="message" align="center" style="width:10%;">
						<xsl:text>Duration </xsl:text>
						<xsl:value-of
							select="sum(TestActivity/TestMethod/MethodResult/@duration)"></xsl:value-of>
						<xsl:text>(s)</xsl:text>
					</TD>
					<!--Nainappa's Changes start -->
					<TD align="Right" width="7%">
						<xsl:if test="@TCStatus mod 10 = 0">
							<a onClick="expandtofailure('DIV{position()}.0')" href="#fail_{@Row}">
								<img alt="Goto First Failure" src="img/FirstDown.ico"
									border="0"></img>
							</a>
						</xsl:if>
					</TD>
					<!-- Nainappa's Changes end -->

					<TD class="passed" align="center">
						Passed -
						<xsl:value-of
							select="(count(TestActivity/TestMethod/MethodResult[@Status='1']) + count(TestActivity/TestMethod/MethodResult[@Status='21']) + count(TestActivity/TestMethod/TestSubMethod/SubMethodResult[@Status='1']) + count(TestActivity/TestMethod/TestSubMethod/SubMethodResult[@Status='21']))"></xsl:value-of>
						<xsl:if test="@TCStatus='11'">
							<xsl:text> *</xsl:text>
						</xsl:if>
					</TD>
					<TD class="failed" align="center">
						Failed -
						<xsl:value-of
							select="(count(TestActivity/TestMethod/MethodResult[@Status='0']) + count(TestActivity/TestMethod/MethodResult[@Status='20']) + count(TestActivity/TestMethod/TestSubMethod/SubMethodResult[@Status='0']) + count(TestActivity/TestMethod/TestSubMethod/SubMethodResult[@Status='20']))"></xsl:value-of>
						<xsl:if test="@TCStatus='10'">
							<xsl:text> *</xsl:text>
						</xsl:if>
					</TD>
					<TD class="warnings" align="center">
						Skipped -
						<xsl:value-of
							select="(count(TestActivity/TestMethod/MethodResult[@Status='2']) + count(TestActivity/TestMethod/TestSubMethod/SubMethodResult[@Status='2']))"></xsl:value-of>
					</TD>
					<!-- <TD class="additional_information" align="Right"> Information - 
						<xsl:value-of select ="(count(TestActivity/TestMethod/MethodResult[@Status='4']) 
						+ count(TestActivity/TestMethod/TestSubMethod/SubMethodResult[@Status='4']))"></xsl:value-of> 
						</TD> -->
				</TR>
			</TABLE>
		</DIV>
		<DIV id="DIV{position()}.0" name="TestActivity" Style="display:block">
			<!--<xsl:apply-templates select="TestFlow"> <xsl:with-param name="TestCasePosition" 
				select="position()"/> </xsl:apply-templates> -->
			<xsl:apply-templates select="TestActivity">
				<xsl:with-param name="TestCasePosition" select="position()" />
			</xsl:apply-templates>
		</DIV>
		<BR></BR>
	</xsl:template>

	<xsl:template match="TestActivity">
		<xsl:param name="TestCasePosition" />
		<DIV id="TestActivity"
			Style="width:100%;POSITION: relative; display:block;float: right;">
			<TABLE cellSpacing="1" cellPadding="1" align="center" Class="TestActivity"
				onClick="toggleMenu('DIV{concat($TestCasePosition,'.',position())}', 'm{concat($TestCasePosition,'.',position())}')">
				<TR>
					<TD class="message">
						<img class="toggle" id="m{concat($TestCasePosition,'.',position())}"
							src="img/Plus.ico" border="0" />
						<xsl:text> </xsl:text>
						<xsl:value-of select="@Desc"></xsl:value-of>
					</TD>
					<TD class="message" align="center" style="width:30%;">
						<xsl:text>Duration </xsl:text>
						<xsl:value-of select="sum(TestMethod/MethodResult/@duration)"></xsl:value-of>
						<xsl:text>(s)</xsl:text>
					</TD>
					<TD class="passed">
						Passed -
						<xsl:value-of
							select="(count(TestMethod/MethodResult[@Status='1']) + count(TestMethod/MethodResult[@Status='21']) + count(TestMethod/TestSubMethod/SubMethodResult[@Status='1']) + count(TestMethod/TestSubMethod/SubMethodResult[@Status='21']))"></xsl:value-of>
					</TD>
					<TD class="failed">
						Failed -
						<xsl:value-of
							select="(count(TestMethod/MethodResult[@Status='0']) + count(TestMethod/MethodResult[@Status='20']) + count(TestMethod/TestSubMethod/SubMethodResult[@Status='0']) + count(TestMethod/TestSubMethod/SubMethodResult[@Status='20']))"></xsl:value-of>
					</TD>
					<TD class="warnings">
						Skipped -
						<xsl:value-of
							select="(count(TestMethod/MethodResult[@Status='2']) + count(TestMethod/TestSubMethod/SubMethodResult[@Status='2']))"></xsl:value-of>
					</TD>
					<!-- <TD class="additional_information"> Information - <xsl:value-of 
						select ="(count(TestMethod/MethodResult[@Status='4']) + count(TestMethod/TestSubMethod/SubMethodResult[@Status='4']))"></xsl:value-of> 
						</TD> -->
				</TR>
			</TABLE>
		</DIV>
		<DIV ID="DIV{concat($TestCasePosition,'.',position())}" Style="display:none">
			<xsl:apply-templates select="TestMethod">
				<xsl:with-param name="TestActivityPosition"
					select="concat($TestCasePosition,'.',position())" />
			</xsl:apply-templates>
		</DIV>
		<DIV />
	</xsl:template>

	<xsl:template match="TestMethod">
		<xsl:param name="TestActivityPosition" />
		<DIV id="TestMethod"
			Style="width:100%;POSITION: relative; display:block;float: right;">
			<TABLE cellSpacing="1" cellPadding="1" align="center" Class="TestMethod">
				<TR>
					<xsl:variable name="text" select="@Desc" />
					<TD class="message1" title="{$text}"
						onClick="toggleMenu('DIV{concat($TestActivityPosition,'.',position())}', 'm{concat($TestActivityPosition,'.',position())}')">
						<img class="toggle" id="m{concat($TestActivityPosition,'.',position())}"
							src="img/Plus.ico" border="0" />
						<xsl:value-of select="@Desc"></xsl:value-of>
					</TD>
					<TD class="message1" align="left" style="width:10%;">
						<xsl:text> [</xsl:text>
						<xsl:value-of select="sum(MethodResult/@duration)"></xsl:value-of>
						<xsl:text>s]</xsl:text>
					</TD>
					<TD style="width:10%;">
						<xsl:if test="MethodResult/@Status='21'">
							<img class="testresult" src="img/True.ico"
								border="0" />
							<font color="#009933">
								<b>
									<xsl:text> Passed*</xsl:text>
								</b>
							</font>
						</xsl:if>
						<xsl:if test="MethodResult/@Status='1'">
							<img class="testresult" src="img/True.ico"
								border="0" />
							<font color="#009933">
								<b>
									<xsl:text> Passed*</xsl:text>
								</b>
							</font>
						</xsl:if>
						<xsl:if test="MethodResult/@Status='20'">
							<img class="testresult" src="img/False.ico"
								border="0" />
							<font color="#ff3333">
								<b>
									<xsl:text> Failed*</xsl:text>
								</b>
							</font>
						</xsl:if>
						<xsl:if test="MethodResult/@Status='0'">
							<img class="testresult" src="img/False.ico"
								border="0" />
							<font color="#ff3333">
								<b>
									<xsl:text> Failed*</xsl:text>
								</b>
							</font>
						</xsl:if>
						<xsl:if test="MethodResult/@Status='2'">
							<img class="testresult" src="img/skip.ico"
								border="0" />
							<font color="#FF8C00">
								<b>
									<xsl:text> Skipped*</xsl:text>
								</b>
							</font>
						</xsl:if>
					</TD>
					<TD class="passed">
						<xsl:if test="MethodResult/@ImagePath">
							<xsl:element name="a">
							<xsl:attribute name="href"><xsl:value-of select="MethodResult/@ImagePath"></xsl:value-of></xsl:attribute>
							<xsl:attribute name="title"><xsl:value-of select="@Desc"></xsl:value-of></xsl:attribute>
							<xsl:attribute name="class"><xsl:text>lb_failures</xsl:text></xsl:attribute>
							ScreenShot
							</xsl:element>
						</xsl:if>
					</TD>
					<TD class="failed">
						<xsl:if test="MethodResult/@WebPagePath">
							<a href="{MethodResult/@WebPagePath}" target="_new">WebPage</a>
						</xsl:if>
					</TD>

					<TD class="warnings">
						<xsl:if test="MethodResult/@VideoRecording">
							<a href="{MethodResult/@VideoRecording}" target="_new">Video Recording</a>
						</xsl:if>
					</TD>
				</TR>
			</TABLE>
		</DIV>
		<Div ID="DIV{concat($TestActivityPosition,'.',position())}" Style="display:none">
			<xsl:variable name="MethodResult" select='"MethodResult"' />
			<xsl:variable name="TestSubMethod" select='"TestSubMethod"' />
			<xsl:variable name="stacktrace" select='"stacktrace"' />
			<xsl:variable name="stacktracelink" select="concat('EXP',$TestActivityPosition,'.',position())" />
			<xsl:variable name="teststatus" select="MethodResult/@Status" />
			<xsl:for-each select="*">
				<xsl:choose>
					<xsl:when test="local-name()=$MethodResult">
						<xsl:call-template name="MethodResult">
							<xsl:with-param name="ExpPosition" select="$stacktracelink" />
						</xsl:call-template>
					</xsl:when>
					<xsl:when test="local-name()=$stacktrace">
						<xsl:call-template name="stacktrace">
							<xsl:with-param name="ExpPosition" select="$stacktracelink" />
							<xsl:with-param name="testStatus" select="$teststatus" />
						</xsl:call-template>
					</xsl:when>
					<xsl:otherwise></xsl:otherwise>
				</xsl:choose>
			</xsl:for-each>
		</Div>
	</xsl:template>
	
	<xsl:template match="stacktrace" name="stacktrace">
		<xsl:param name="ExpPosition" />
		<xsl:param name="testStatus"/>
		<a href="#x" class="overlay" id="{$ExpPosition}"></a> 
				<div class="popup">
				<xsl:choose>
					<xsl:when test="$testStatus=2">
						<h2>Configuration Failure</h2>
						<h3><xsl:value-of select="@configMethod"></xsl:value-of></h3>
					</xsl:when>
					<xsl:otherwise>
						<h2>Failure Stack Trace</h2>
					</xsl:otherwise>
				</xsl:choose>
				<p id="exception"> <xsl:value-of select="." disable-output-escaping="yes"></xsl:value-of> </p> 
				<a class="close" href="#close"></a> 
				</div>
	</xsl:template>

	<xsl:template match="MethodResult" name="MethodResult">
	<xsl:param name="ExpPosition" />
		<DIV id="MethodResult">
			<TABLE cellSpacing="1" cellPadding="1" align="center" Class="messages">
				<xsl:element name="TR">
					<xsl:if test="position()mod 2">
						<xsl:attribute name="class">M1</xsl:attribute>
					</xsl:if>
					<xsl:if test="not(position()mod 2)">
						<xsl:attribute name="class">M2</xsl:attribute>
					</xsl:if>
	
					<xsl:element name="TD">
						<!--Nainappa -> To get ID from xml and set as ID for the html tag <td> 
							- start -->
						<xsl:attribute name="id">
								<xsl:if test="@ID">
									<xsl:value-of select="@ID" />
								</xsl:if>
							</xsl:attribute>
						<!--Nainappa -> To get ID from xml and set as ID for the html tag <td> 
							- end -->
	
						<xsl:attribute name="class">
								<xsl:if test="@Status='0' or @Status='20'">failed</xsl:if>
								<xsl:if test="@Status='3'">information</xsl:if>
								<xsl:if test="@Status='4'">additional_information</xsl:if>
								<xsl:if test="@Status='2'">warnings</xsl:if>
								<xsl:if test="@Status='1' or @Status='21'">passed</xsl:if>
						</xsl:attribute>
						<xsl:choose>
							<xsl:when test="../stacktrace and (@Status='2' or @Status='0' or @Status='20')">
								<a href="#{$ExpPosition}" id="">
									<xsl:value-of select="." disable-output-escaping="yes"></xsl:value-of>
								</a>
							</xsl:when>
							<xsl:otherwise>
								<xsl:value-of select="." disable-output-escaping="yes"></xsl:value-of>
							</xsl:otherwise>
						</xsl:choose>
						<xsl:if test="@ID">
							<div style="text-align:	right;">
								<a href="#" style="color:black;text-decoration:none;font-size:10px"
									onClick="collapseall()">^ Back to Top</a>
							</div>
						</xsl:if>
					</xsl:element>
				</xsl:element>
			</TABLE>
		</DIV>
	</xsl:template>
</xsl:stylesheet>